/**
 * GET/POST /cron/generate-trivia-questions
 *
 * Phase 49 (2026-05-05) rewrite — two-track refill pipeline.
 *
 * **Track A (deterministic, $0):** strategy categories generated from
 * `solved_spots_gold` + `memory_charts_gold` via the same engine training
 * games use. NO Grok involvement.
 *   gto_theory, gto_scenarios, cash_game_situations, mtt_situations, icm_chip_ev
 *
 * **Track B (Grok-3 + validator gate):** fact categories generated by Grok
 * with a 5-layer validator and 60-day dedup.
 *   poker_history, famous_hands, player_profiles, tournament_facts, rule_knowledge
 *
 * Each run does up to MAX_BATCHES_PER_RUN batches across all categories,
 * preferring the most-undertarget category each iteration. Track A batches
 * are nearly free (no Grok call). Track B batches cost ~$0.002 each.
 *
 * Auth: /cron/* middleware chain (Bearer CRON_SECRET).
 *
 * Env vars required:
 *   XAI_API_KEY (Track B only)
 *   NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 */
import type { Context } from 'hono';
import { getSupabase } from '../lib/supabase.js';
import { getGrokClient } from '../lib/grok.js';
import { validateBatch, type TriviaQuestion } from '../lib/triviaValidator.js';

// ─── Configuration ─────────────────────────────────────────────────────────

const TARGET_PER_CATEGORY = 1500;
const DIFFICULTY_DISTRIBUTION: Record<string, number> = { easy: 20, medium: 50, hard: 30 };
const MAX_BATCHES_PER_RUN = 6; // up to 6 batches per cron tick
const TRACK_A_BATCH_SIZE = 100; // deterministic: lots, fast
const TRACK_B_BATCH_SIZE = 10;  // Grok: small, cost-controlled

const TRACK_A_CATEGORIES = ['gto_theory', 'gto_scenarios', 'cash_game_situations', 'mtt_situations', 'icm_chip_ev'];
const TRACK_B_CATEGORIES = ['poker_history', 'famous_hands', 'player_profiles', 'tournament_facts', 'rule_knowledge'];

// ─── Track A — deterministic helpers (ported from scripts/trivia-deterministic-seed.js) ──

const RANK_VAL: Record<string, number> = {
  '2':0,'3':1,'4':2,'5':3,'6':4,'7':5,'8':6,'9':7,'T':8,'J':9,'Q':10,'K':11,'A':12,
};

const ACTION_LABELS: Record<string, string> = {
  c:'Check', x:'Check', f:'Fold', fold:'Fold', push:'Push All-In',
  b16:'Bet 16% pot', b20:'Bet 20% pot', b25:'Bet 25% pot', b33:'Bet 33% pot',
  b40:'Bet 40% pot', b45:'Bet 45% pot', b50:'Bet 50% pot', b55:'Bet 55% pot',
  b60:'Bet 60% pot', b66:'Bet 67% pot', b75:'Bet 75% pot', b80:'Bet 80% pot',
  b100:'Bet pot', b125:'Bet 125% pot', b150:'Overbet 150%', b200:'Overbet 200%',
  b300:'Overbet 300%', allin:'All-In', r:'Raise',
};

const VILLAIN_MAP: Record<string, string> = {
  BTN:'BB', SB:'BB', BB:'BTN', UTG:'BB', MP:'BB', CO:'BTN', HJ:'CO', 'UTG+1':'BB', 'MP+1':'BB',
};

function getActionLabel(code: string): string {
  if (ACTION_LABELS[code]) return ACTION_LABELS[code]!;
  const bm = code.match(/^b(\d+)$/);
  if (bm) return `Bet ${bm[1]}% pot`;
  const rm = code.match(/^r(\d+)$/);
  if (rm) return `Raise ${rm[1]}%`;
  return code.toUpperCase();
}

function parseBoardFromHash(hash: string): string[] {
  if (!hash) return [];
  const parts = hash.split('_');
  const boardStr = parts[parts.length - 1] || '';
  if (boardStr.length < 4) return [];
  const cards: string[] = [];
  for (let i = 0; i < boardStr.length; i += 2) {
    if (i + 1 < boardStr.length) {
      const card = boardStr.substring(i, i + 2);
      if (/^[2-9TJQKA][shdc]$/i.test(card)) cards.push(card);
    }
  }
  return cards;
}

function extractPositionFromHash(hash: string): string {
  if (!hash) return 'BTN';
  const POSITIONS = ['BTN', 'SB', 'BB', 'UTG', 'MP', 'CO', 'HJ'];
  for (const part of hash.split('_')) {
    if (POSITIONS.includes(part.toUpperCase())) return part.toUpperCase();
  }
  return 'BTN';
}

function hashSeed(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) { h = ((h << 5) - h) + str.charCodeAt(i); h |= 0; }
  return Math.abs(h);
}

function classifyDifficulty(maxFreq: number): string {
  if (maxFreq >= 0.80) return 'easy';
  if (maxFreq <= 0.55) return 'hard';
  return 'medium';
}

interface DetQuestion {
  question: string;
  options: string[];
  correct_index: number;
  explanation: string;
  difficulty: string;
  subcategory: string;
}

function buildDetQuestionFromScenario(scenario: any, idx: number, category: string): DetQuestion | null {
  const sm = scenario.strategy_matrix || {};
  const actions: string[] = sm.actions || [];
  const frequencies: Record<string, Record<string, number>> = sm.frequencies || {};
  if (actions.length === 0) return null;

  const sampleAction = actions.find(a => frequencies[a]) || actions[0]!;
  const handFreqs = frequencies[sampleAction] || {};
  const allHands = Object.keys(handFreqs).filter(h => {
    if (!h || h.length < 2) return false;
    return actions.some(a => {
      const f = frequencies[a]?.[h];
      return typeof f === 'number' && f > 0;
    });
  });
  if (allHands.length === 0) return null;

  const seed = hashSeed(`${scenario.scenario_hash || scenario.id}_${idx}`);
  const heroHand = allHands[seed % allHands.length]!;

  const handActions: Record<string, number> = {};
  const validActions: string[] = [];
  let optimalAction = '';
  let maxFreq = -1;
  for (const a of actions) {
    const f = frequencies[a]?.[heroHand];
    if (typeof f === 'number' && f >= 0 && f <= 1) {
      handActions[a] = f;
      validActions.push(a);
      if (f > maxFreq) { maxFreq = f; optimalAction = a; }
    }
  }
  if (!optimalAction || validActions.length === 0) return null;

  const gtoFrequencies: Record<string, number> = {};
  for (const a of validActions) gtoFrequencies[a] = Math.round((handActions[a] || 0) * 100);
  const total = Object.values(gtoFrequencies).reduce((s, v) => s + v, 0);
  if (total > 0 && total !== 100) {
    for (const k of Object.keys(gtoFrequencies)) gtoFrequencies[k] = Math.round(gtoFrequencies[k]! * 100 / total);
    const newTotal = Object.values(gtoFrequencies).reduce((s, v) => s + v, 0);
    if (newTotal !== 100) gtoFrequencies[optimalAction] = (gtoFrequencies[optimalAction] || 0) + (100 - newTotal);
  }

  const optionsArr = validActions.slice(0, 4).map(a => ({ id: a, text: getActionLabel(a) }));
  const allFillers = ['f', 'c', 'b33', 'b75', 'allin', 'r', 'b50', 'b100'];
  while (optionsArr.length < 4) {
    const fa = allFillers.find(x => !optionsArr.some(o => o.id === x));
    if (!fa) break;
    optionsArr.push({ id: fa, text: getActionLabel(fa) });
  }
  if (optionsArr.length < 4) return null;

  const board = parseBoardFromHash(scenario.scenario_hash || '');
  const heroPos = extractPositionFromHash(scenario.scenario_hash || '');
  const street = scenario.street || 'flop';

  const freqPct = (maxFreq * 100).toFixed(0);
  let explanation: string;
  if (maxFreq >= 0.95) {
    explanation = `GTO solver: Pure ${getActionLabel(optimalAction)} (${freqPct}%). ${heroHand} has a clear optimal line on the ${street}.`;
  } else {
    const mixedParts = validActions
      .filter(a => (handActions[a] || 0) > 0.01)
      .sort((a, b) => (handActions[b] || 0) - (handActions[a] || 0))
      .map(a => `${getActionLabel(a)} ${((handActions[a] || 0) * 100).toFixed(0)}%`)
      .join(', ');
    explanation = `GTO solver mixes: ${mixedParts}. Primary line is ${getActionLabel(optimalAction)} at ${freqPct}%.${maxFreq < 0.6 ? ' This is a close GTO spot.' : ''}`;
  }
  if (board.length > 0) explanation = `Board: ${board.join(' ')}. ${explanation}`;

  const questionText = street === 'preflop'
    ? `You hold ${heroHand} in ${heroPos} preflop (${scenario.stack_depth || 100}BB). What is the GTO play?`
    : `You hold ${heroHand} on the ${street}. Board: ${board.join(' ')}. What is the GTO play?`;

  const correctIdx = optionsArr.findIndex(o => o.id === optimalAction);
  if (correctIdx < 0) return null;

  return {
    question: questionText,
    options: optionsArr.map(o => o.text),
    correct_index: correctIdx,
    explanation,
    difficulty: classifyDifficulty(maxFreq),
    subcategory: `det:${scenario.scenario_hash || scenario.id}:${heroHand}`,
  };
}

const TRACK_A_SOURCES: Record<string, Array<{ table: string; filter: string }>> = {
  gto_theory: [
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.flop' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.turn' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.river' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.9max_cash&street=eq.flop' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.9max_cash&street=eq.turn' },
  ],
  gto_scenarios: [
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.river' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.turn' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.9max_cash&street=eq.turn' },
  ],
  cash_game_situations: [
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.flop' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.turn' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.cash&street=eq.river' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.9max_cash&street=eq.flop' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.9max_cash&street=eq.turn' },
  ],
  mtt_situations: [
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_chipev&street=eq.river' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_chipev&street=eq.turn' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_chipev&street=eq.flop' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_9max_chipev&street=eq.turn' },
  ],
  icm_chip_ev: [
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_icm&street=eq.river' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_icm&street=eq.turn' },
    { table: 'solved_spots_gold', filter: '&game_type=eq.mtt_icm&street=eq.flop' },
  ],
};

async function fetchScenarioPool(category: string, page = 0, pageSize = 1000): Promise<any[]> {
  const sources = TRACK_A_SOURCES[category] || [];
  if (sources.length === 0) return [];
  // Pick a source by category-and-tick variety
  const src = sources[(page + Date.now() / 1000 / 60 | 0) % sources.length]!;
  const sb = getSupabase();
  const select = 'id,scenario_hash,street,stack_depth,game_type,strategy_matrix';
  // Hono supabase wrapper: use `from(...).select(...)` rather than raw url
  // Filter is in URL form "&game_type=eq.X&street=eq.Y" — parse to chain
  let query = sb.from(src.table).select(select);
  for (const part of src.filter.split('&').filter(Boolean)) {
    const [col, expr] = part.split('=');
    if (!col || !expr) continue;
    if (expr.startsWith('eq.')) query = query.eq(col, expr.slice(3));
  }
  const { data, error } = await query.range(page * pageSize, (page + 1) * pageSize - 1);
  if (error) {
    console.warn(`[trivia/track-A] pool fetch error for ${category}: ${error.message}`);
    return [];
  }
  return data || [];
}

async function generateTrackABatch(category: string, target: number, existing: Set<string>): Promise<TriviaQuestion[]> {
  // Try up to 3 pool pages to gather enough new questions
  const out: TriviaQuestion[] = [];
  for (let page = 0; page < 3 && out.length < target; page++) {
    const pool = await fetchScenarioPool(category, page);
    if (pool.length === 0) break;
    for (let i = 0; i < pool.length * 4 && out.length < target; i++) {
      const sc = pool[i % pool.length];
      const q = buildDetQuestionFromScenario(sc, Math.floor(i / pool.length), category);
      if (!q) continue;
      if (existing.has(q.subcategory)) continue;
      existing.add(q.subcategory);
      out.push({
        category,
        difficulty: q.difficulty,
        question: q.question,
        options: q.options,
        correct_index: q.correct_index,
        explanation: q.explanation,
        subcategory: q.subcategory,
        created_at: new Date().toISOString(),
        last_used_at: null,
      } as TriviaQuestion);
    }
  }
  return out;
}

// ─── Track B — Grok prompts (preserved from prior version) ────────────────

interface CategoryDef {
  id: string;
  name: string;
  subcategories: string[];
}

const TRACK_B_CATEGORIES_DEF: CategoryDef[] = [
  { id: 'poker_history', name: 'Poker History', subcategories: [
    'Origins and evolution of poker', 'Important dates in poker history', 'Historic poker venues and casinos',
    'Poker in pop culture and media', 'Evolution of online poker', 'Historic WSOP moments', 'Legendary poker games',
  ]},
  { id: 'famous_hands', name: 'Famous Hands', subcategories: [
    'WSOP Main Event famous hands', 'High Stakes Poker iconic moments', 'Poker After Dark memorable plays',
    'Bad beats and coolers', 'Bluffs that made history', 'Heads-up championship hands', 'Notable tournament final table hands',
  ]},
  { id: 'player_profiles', name: 'Player Profiles', subcategories: [
    'WSOP bracelet winners', 'Poker Hall of Fame members', 'International poker champions',
    'Online poker legends', 'Cash game specialists', 'Tournament grinders', 'Poker commentators and personalities',
  ]},
  { id: 'tournament_facts', name: 'Tournament Facts', subcategories: [
    'WSOP history and records', 'WPT history and champions', 'EPT and international tours',
    'High roller events', 'Online tournament milestones', 'Prize pool records', 'Biggest poker tournaments ever',
  ]},
  { id: 'rule_knowledge', name: 'Rules & Etiquette', subcategories: [
    'Hand rankings and terminology', 'Betting rules and structures', 'Tournament rules (TDA)',
    'Cash game procedures', 'Dealer responsibilities', 'Poker etiquette', 'Angle shooting and illegal moves',
  ]},
];

const AG1_SYSTEM_PROMPT = `You are a poker historian and rules expert generating trivia questions. Output ONLY valid JSON. Be FACTUALLY ACCURATE — every fact must be verifiable from public sources.`;

async function generateTrackBBatch(category: CategoryDef, subcategory: string, difficulty: string, count: number): Promise<TriviaQuestion[]> {
  const grok = getGrokClient();
  const prompt = `Generate exactly ${count} unique poker trivia questions.

CATEGORY: ${category.name}
TOPIC FOCUS: ${subcategory}
DIFFICULTY: ${difficulty}

Rules:
- Each question has exactly 4 multiple-choice options
- Exactly one option is correct (set correct_index 0-3)
- The correct answer must be 100% factually verifiable from public sources
- Distractors must be plausible but clearly wrong (no joke answers)
- "${difficulty}" means: easy = casual fans know it; medium = enthusiasts know it; hard = serious students of the game
- Provide a 1-2 sentence explanation citing a specific source/event/year
- Avoid duplicating well-known questions

Return ONLY this JSON shape (no markdown, no extra text):
{"questions":[{"question":"...","options":["A","B","C","D"],"correct_index":0,"explanation":"...","subcategory":"${subcategory}"}]}`;

  try {
    const response = await grok.chat.completions.create({
      model: 'grok-3-mini',
      messages: [
        { role: 'system', content: AG1_SYSTEM_PROMPT },
        { role: 'user', content: prompt },
      ],
      response_format: { type: 'json_object' },
      temperature: 0.7,
      max_tokens: 4000,
      // @ts-expect-error reasoning_effort is xAI-specific
      reasoning_effort: 'low',
    });

    const content = response.choices[0]?.message?.content;
    if (!content) return [];
    const parsed = JSON.parse(content);
    const questions: any[] = Array.isArray(parsed) ? parsed : parsed.questions || [];

    return questions
      .filter(q =>
        q.question && q.options?.length === 4 &&
        typeof q.correct_index === 'number' && q.correct_index >= 0 && q.correct_index <= 3 &&
        q.explanation && q.explanation.length > 30,
      )
      .map(q => ({
        category: category.id,
        difficulty,
        question: q.question.trim(),
        options: q.options.map((o: string) => o.trim()),
        correct_index: q.correct_index,
        explanation: q.explanation.trim(),
        subcategory: `grok:${subcategory.slice(0, 60)}`,
        created_at: new Date().toISOString(),
        last_used_at: null,
      }));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(`[trivia/track-B] generation error ${category.name}/${subcategory}/${difficulty}: ${msg}`);
    return [];
  }
}

async function checkForDuplicates(newQuestion: string, category: string): Promise<boolean> {
  const keywords = newQuestion.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(' ').filter(w => w.length > 4).slice(0, 5);
  if (keywords.length === 0) return false;
  const { data: existing } = await getSupabase()
    .from('trivia_questions').select('question').eq('category', category).limit(500);
  if (!existing) return false;
  for (const eq of existing as { question: string }[]) {
    const ew = eq.question.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(' ').filter(w => w.length > 4);
    const overlap = keywords.filter(k => ew.includes(k)).length;
    if (overlap >= 3 || (keywords.length <= 3 && overlap === keywords.length)) return true;
  }
  return false;
}

// ─── Pool stats ───────────────────────────────────────────────────────────

interface PoolStat {
  total: number;
  easy: number;
  medium: number;
  hard: number;
}

async function getPoolStats(): Promise<Record<string, PoolStat>> {
  const stats: Record<string, PoolStat> = {};
  const allCategories = [...TRACK_A_CATEGORIES, ...TRACK_B_CATEGORIES];

  for (const catId of allCategories) {
    const sb = getSupabase();
    const { count: total } = await sb.from('trivia_questions').select('*', { count: 'exact', head: true }).eq('category', catId);
    const { count: easy } = await sb.from('trivia_questions').select('*', { count: 'exact', head: true }).eq('category', catId).eq('difficulty', 'easy');
    const { count: medium } = await sb.from('trivia_questions').select('*', { count: 'exact', head: true }).eq('category', catId).eq('difficulty', 'medium');
    const { count: hard } = await sb.from('trivia_questions').select('*', { count: 'exact', head: true }).eq('category', catId).eq('difficulty', 'hard');
    stats[catId] = { total: total ?? 0, easy: easy ?? 0, medium: medium ?? 0, hard: hard ?? 0 };
  }
  return stats;
}

interface NeedItem {
  categoryId: string;
  difficulty: 'easy' | 'medium' | 'hard';
  needed: number;
  track: 'A' | 'B';
}

function determineNeeds(stats: Record<string, PoolStat>): NeedItem[] {
  const needs: NeedItem[] = [];
  for (const catId of [...TRACK_A_CATEGORIES, ...TRACK_B_CATEGORIES]) {
    const s = stats[catId];
    if (!s || s.total >= TARGET_PER_CATEGORY) continue;
    const track = TRACK_A_CATEGORIES.includes(catId) ? 'A' : 'B';
    for (const [diff, pct] of Object.entries(DIFFICULTY_DISTRIBUTION)) {
      const targetCount = Math.floor(TARGET_PER_CATEGORY * pct / 100);
      const current = s[diff as 'easy' | 'medium' | 'hard'];
      const needed = Math.max(0, targetCount - current);
      if (needed > 0) needs.push({ categoryId: catId, difficulty: diff as any, needed, track });
    }
  }
  // Prioritize biggest gaps first; within a tie, prefer Track A (free)
  needs.sort((a, b) => {
    if (a.needed !== b.needed) return b.needed - a.needed;
    return a.track === 'A' ? -1 : 1;
  });
  return needs;
}

// ─── Hono handler ─────────────────────────────────────────────────────────

export async function generateTriviaQuestions(c: Context) {
  const startTs = Date.now();
  try {
    const stats = await getPoolStats();
    const totalNow = Object.values(stats).reduce((s, v) => s + v.total, 0);
    const targetTotal = (TRACK_A_CATEGORIES.length + TRACK_B_CATEGORIES.length) * TARGET_PER_CATEGORY;

    if (totalNow >= targetTotal) {
      return c.json({ success: true, message: 'pool complete', totalNow, targetTotal, stats });
    }

    const needs = determineNeeds(stats);
    if (needs.length === 0) return c.json({ success: true, message: 'all categories at target', stats });

    let generated = 0;
    let trackACalls = 0;
    let trackBCalls = 0;
    const results: any[] = [];

    // Subcategory dedup cache per Track A category (loaded lazily)
    const detExisting: Record<string, Set<string>> = {};

    for (let batch = 0; batch < MAX_BATCHES_PER_RUN && batch < needs.length; batch++) {
      const need = needs[batch]!;

      if (need.track === 'A') {
        // Track A — deterministic
        if (!detExisting[need.categoryId]) {
          const { data } = await getSupabase()
            .from('trivia_questions').select('subcategory').eq('category', need.categoryId).like('subcategory', 'det:%').limit(5000);
          detExisting[need.categoryId] = new Set((data || []).map((r: any) => r.subcategory).filter(Boolean));
        }
        const want = Math.min(TRACK_A_BATCH_SIZE, need.needed);
        const allQs = await generateTrackABatch(need.categoryId, want * 3, detExisting[need.categoryId]!);
        // Filter to the desired difficulty bucket
        const qs = allQs.filter(q => q.difficulty === need.difficulty).slice(0, want);
        if (qs.length > 0) {
          const { valid: validQs, rejected } = validateBatch(qs);
          if (rejected.length > 0) console.warn(`[trivia/track-A] ${need.categoryId} rejected ${rejected.length} questions`);
          if (validQs.length > 0) {
            const { data, error } = await getSupabase().from('trivia_questions').insert(validQs).select();
            if (error) console.warn(`[trivia/track-A] insert error: ${error.message}`);
            else {
              generated += data?.length ?? 0;
              results.push({ track: 'A', category: need.categoryId, difficulty: need.difficulty, generated: data?.length ?? 0 });
            }
          }
        }
        trackACalls++;
      } else {
        // Track B — Grok
        const catDef = TRACK_B_CATEGORIES_DEF.find(c => c.id === need.categoryId);
        if (!catDef) continue;
        const subcat = catDef.subcategories[Math.floor(Math.random() * catDef.subcategories.length)]!;
        const want = Math.min(TRACK_B_BATCH_SIZE, need.needed);
        const qs = await generateTrackBBatch(catDef, subcat, need.difficulty, want);
        const uniqueQs: TriviaQuestion[] = [];
        for (const q of qs) {
          if (!(await checkForDuplicates(q.question, need.categoryId))) uniqueQs.push(q);
        }
        if (uniqueQs.length > 0) {
          const { valid: validQs, rejected } = validateBatch(uniqueQs);
          if (rejected.length > 0) console.warn(`[trivia/track-B] ${need.categoryId}/${subcat} rejected ${rejected.length}`);
          if (validQs.length > 0) {
            const { data, error } = await getSupabase().from('trivia_questions').insert(validQs).select();
            if (error) console.warn(`[trivia/track-B] insert error: ${error.message}`);
            else {
              generated += data?.length ?? 0;
              results.push({ track: 'B', category: need.categoryId, subcategory: subcat, difficulty: need.difficulty, generated: data?.length ?? 0 });
            }
          }
        }
        trackBCalls++;
      }

      if (batch < MAX_BATCHES_PER_RUN - 1) await new Promise(r => setTimeout(r, 500));
    }

    const after = await getPoolStats();
    const newTotal = Object.values(after).reduce((s, v) => s + v.total, 0);

    return c.json({
      success: true,
      generated,
      trackACalls,
      trackBCalls,
      previousTotal: totalNow,
      newTotal,
      targetTotal,
      progress: `${Math.round((newTotal / targetTotal) * 100)}%`,
      elapsedMs: Date.now() - startTs,
      results,
      stats: after,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn('[generate-trivia-questions] fatal:', msg);
    return c.json({ success: false, error: msg }, 500);
  }
}
