#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
#  A HOOK THAT DOES NOT RUN IS A COMMENT
# ═══════════════════════════════════════════════════════════════════════════
#
# WHY THIS EXISTS (2026-08-23)
#
# Five Vercel deployments sat BLOCKED, all of them commits authored
# 'Agent <agent@smarter.poker>'. The obvious fix is a pre-commit guard on the
# author. Writing one exposed something much worse: THE PRE-COMMIT HOOK HAS
# NEVER RUN IN THIS REPO, and in 38 of 47 agent worktrees NO hook ran at all.
#
# Two independent faults, each of which git reports by saying nothing:
#
#   1. core.hooksPath pointed at `.husky/_`. That directory is GITIGNORED and
#      generated by `husky` during `npm install`. A git worktree starts with no
#      node_modules, so it was never generated there. git finds no hooks and
#      runs none - no warning, no error, exit 0. Every guard in this estate
#      (one-worktree-per-agent, the orphan reference-transaction guard, the
#      never-push-a-red-test pre-push gate) was silently absent in exactly the
#      trees where agents do their work.
#
#   2. `.husky/pre-commit` was tracked at mode 644. git SKIPS a hook that is
#      not executable, again silently. So even in the main clone, where
#      `.husky/_` existed, pre-commit never ran. In World Hub that meant the
#      merge-conflict-marker check and the transpilePackages guard - both
#      written after real production outages - were decorative.
#
# THE SHAPE THAT WORKS, and the only one that survives a fresh worktree:
#
#   core.hooksPath = .husky   (TRACKED, so it exists the moment a tree does)
#   every hook file mode 755  (or git skips it and tells nobody)
#
# smarter-poker-commander already had exactly this, which is why its worktrees
# were the only ones fully guarded.
#
# This script asserts that shape and repairs it. It is idempotent, it is called
# by scripts/agent-workspace.sh for every worktree it creates, and it is safe
# to run by hand in any clone:
#
#     bash scripts/ensure-hooks.sh            # repair and report
#     bash scripts/ensure-hooks.sh --check    # report only, exit 1 if broken
#
set -euo pipefail

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
PROBLEMS=0
say() { printf '  %s\n' "$*"; }

# ── 1. hooksPath must resolve to a directory that is committed ──────────────
WANT=".husky"
[ -d "$ROOT/$WANT" ] || { say "no $WANT/ in this repo - nothing to wire."; exit 0; }

HAVE=$(git config core.hooksPath || echo "")
if [ "$HAVE" != "$WANT" ]; then
  if [ "$CHECK_ONLY" = "1" ]; then
    say "BROKEN core.hooksPath='${HAVE:-<unset>}' - wants '$WANT'"
    say "        '${HAVE:-<default>}' is not tracked, so a fresh worktree has no hooks at all."
    PROBLEMS=1
  else
    # NOTE: core.hooksPath lives in the SHARED config, so setting it here fixes
    # every existing worktree of this repo at the same time.
    git config core.hooksPath "$WANT"
    say "core.hooksPath: '${HAVE:-<unset>}' -> '$WANT' (fixes every worktree of this repo)"
  fi
fi

# ── 2. every tracked hook must be executable ───────────────────────────────
# The mode has to change IN GIT, not just on disk: a fresh clone or worktree
# materialises whatever mode the index records, so `chmod +x` alone lasts until
# the next tree is created and then the hook is silently skipped again.
for f in $(git ls-files "$WANT"); do
  case "$(basename "$f")" in *.md|*.txt|README*) continue ;; esac
  MODE=$(git ls-files -s "$f" | awk '{print substr($1,4)}')
  [ "$MODE" = "755" ] && continue
  if [ "$CHECK_ONLY" = "1" ]; then
    say "BROKEN $f is mode $MODE - git skips non-executable hooks WITHOUT SAYING SO"
    PROBLEMS=1
  else
    chmod +x "$f"
    git update-index --chmod=+x "$f" 2>/dev/null || true
    say "$f: mode $MODE -> 755 (was being skipped silently)"
  fi
done

# ── 3. prove it, rather than assume it ─────────────────────────────────────
# The whole point of this file is that both failures above are invisible. So
# the last step is not a config read, it is a real hook invocation.
RESOLVED="$ROOT/$(git config core.hooksPath || echo .git/hooks)"
if [ -x "$RESOLVED/pre-commit" ]; then
  say "verified: git will run $RESOLVED/pre-commit"
else
  say "STILL BROKEN: $RESOLVED/pre-commit is missing or not executable"
  PROBLEMS=1
fi

[ "$PROBLEMS" = "0" ] || { [ "$CHECK_ONLY" = "1" ] && exit 1; exit 1; }
exit 0
